import { useRef, useCallback } from 'react';
import type { ChordVoicing, NoteName } from './chordData';
import { ChordDiagram } from './ChordDiagram';
import { Fretboard } from './Fretboard';
import { ShapeGrid } from './ShapeGrid';


interface ExportViewProps {
  selectedKey: NoteName;
  voicings: ChordVoicing[];
  optimal: ChordVoicing[];
  optimalSet: Set<string>;
  grouped: Map<number, ChordVoicing[]>;
  showBarre: boolean;
}

// Fixed-width export layout rendered offscreen, then captured to PNG
export function useExportImage({ selectedKey, voicings, optimal, optimalSet, grouped, showBarre }: ExportViewProps) {
  const containerRef = useRef<HTMLDivElement>(null);

  const exportImage = useCallback(async () => {
    const el = containerRef.current;
    if (!el) return;
    // Show temporarily for rendering
    el.style.display = 'block';
    // Wait for SVG rendering
    await new Promise(r => setTimeout(r, 100));
    const { default: html2canvas } = await import('html2canvas-pro');
    const canvas = await html2canvas(el, {
      backgroundColor: getComputedStyle(document.documentElement).getPropertyValue('--crust').trim(),
      scale: 2,
    });
    el.style.display = 'none';
    const a = document.createElement('a');
    a.href = canvas.toDataURL('image/png');
    a.download = `chordao-${selectedKey}.png`;
    a.click();
  }, [selectedKey]);

  const ExportContainer = (
    <div
      ref={containerRef}
      style={{ display: 'none', position: 'fixed', left: '-9999px', top: 0, width: 1200, zIndex: -1 }}
    >
      <div style={{ padding: 32, fontFamily: 'Inter, system-ui, sans-serif', color: 'var(--text)' }}>
        {/* Header */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 24 }}>
          <img src={`${import.meta.env.BASE_URL}logo.svg`} alt="" style={{ width: 32, height: 32 }} />
          <div>
            <div style={{ fontSize: 20, fontWeight: 'bold', color: 'var(--text)' }}>Chordao — Key of {selectedKey}</div>
            <div style={{ fontSize: 11, color: 'var(--overlay1)' }}>E/Em/A/Am shape derivation · chordao.w-mai.github.io</div>
          </div>
        </div>

        {/* Shape Grid */}
        <div style={{ marginBottom: 20 }}>
          <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--subtext1)', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 8 }}>
            Shape Grid
          </div>
          <ShapeGrid voicings={voicings} optimal={optimal} light={false} />
        </div>

        {/* Fretboard */}
        <div style={{ marginBottom: 20 }}>
          <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--subtext1)', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 8 }}>
            Fretboard Overview
          </div>
          <Fretboard voicings={voicings} optimal={optimal} light={false} />
        </div>

        {/* Chord Diagrams */}
        <div>
          <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--subtext1)', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 8 }}>
            Chord Diagrams
          </div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 16 }}>
            {[1, 2, 3, 4, 5, 6].map(degree => {
              const dv = grouped.get(degree) ?? [];
              return dv.map(v => (
                <div key={`${v.name}-${v.shapeOrigin}`} style={{ width: 140 }}>
                  <ChordDiagram
                    voicing={v}
                    highlighted={optimalSet.has(`${v.name}-${v.shapeOrigin}`)}
                    light={false}
                    showBarre={showBarre}
                  />
                </div>
              ));
            })}
          </div>
        </div>

        {/* Footer */}
        <div style={{ marginTop: 24, paddingTop: 12, borderTop: '1px solid var(--surface0)', fontSize: 10, color: 'var(--overlay0)', textAlign: 'center' }}>
          Generated by Chordao · github.com/W-Mai/chordao · MIT
        </div>
      </div>
    </div>
  );

  return { exportImage, ExportContainer };
}
